insert into cryptolink_symbols (symbol, coingecko_id, active)
values ('FLR', 'flare-networks', true),
       ('EURC', 'euro-coin', true),
       ('PANCAKE', 'pancakeswap-token', true),
       ('AERO', 'aerodrome-finance', true),
       ('DASH', 'dash', true),
       ('SEI', 'sei-network', true),
       ('VIRTUAL', 'virtual-protocol', true),
       ('SUN', 'sun-token', true),
       ('CRV', 'curve-dao-token', true),
       ('FDUSD', 'first-digital-usd', true),
       ('GNO', 'gnosis', true),
       ('LUNC', 'terra-luna', true),
       ('JTO', 'jito-governance-token', true),
       ('NFT', 'apenft', true),
       ('BONK', 'bonk', true),
       ('TIA', 'celestia', true),
       ('ZRO', 'layerzero', true),
       ('KAITO', 'kaito', true),
       ('LDO', 'lido-dao', true),
       ('SPX', 'spx6900', true),
       ('BTT', 'bittorrent', true),
       ('BSV', 'bitcoin-cash-sv', true),
       ('MON', 'monad', true),
       ('STX', 'blockstack', true),
       ('PENDLE', 'pendle', true),
       ('CFX', 'conflux-token', true),
       ('IMX', 'immutable-x', true),
       ('JASMY', 'jasmycoin', true),
       ('DCR', 'decred', true),
       ('XPL', 'plasma', true)
on conflict (symbol) do update
set coingecko_id = excluded.coingecko_id,
    active      = excluded.active;